#The world where the lobby is. default: world
lobby-world:
  world

#The world where the survival world is. default: world
survival-world:
  world

coordinates:
  #The coordinates of the lobby. default: x: 0, y: 63, z: 0
  - lobby:
    - x: 0.0
    - y: 63.0
    - z: 0.0
  #The coordinates of the survival world. default: x: 0, y: 63, z: 0
  - survival:
    - x: 0.0
    - y: 63.0
    - z: 0.0