#The world where the lobby is. default: world
lobby-world:
  world

#The coordinates of the lobby. default: x: 0, y: 63, z: 0
coordinates:
  - lobby:
    - x: 0.0
    - y: 63.0
    - z: 0.0
  - survival:
    - x: 0.0
    - y: 63.0
    - z: 0.0