name: LilithServerEssential
version: '${version}'
author: Lilith-Monodia
website: https://github.com/Monodia3007/LilithServerEssential
main: eu.lilithmonodia.lilithserveressential.LilithServerEssential
api-version: 1.19
commands:
  hub:
    description: A command made to teleport a player to the hub
    usage: /hub
    aliases:
      - lobby
    permission: LilithServerEssential.hub
    permission-message: You don't have <permission>
  sethub:
    description: A command to change the hub world
    usage: /sethub <world-name> <x> <y> <z>
    aliases:
      - setlobby
    permission: LilithServerEssential.sethub
    permission-message: You don't have <permission>
  survivalworld:
    description: A command to teleport to the spawn of the survival world
    usage: /survivalworld
    permission: LilithServerEssential.survivalworld
    permission-message: You don't have <permission>
  setsurvivalworld:
    description: A command to change the survival world
    usage: /setsurvivalworld <world-name> <x> <y> <z>
    permission: LilithServerEssential.setsurvivalworld
    permission-message: You don't have <permission>